import { Profile, ServicePhoto, Testimonial, SystemSettings } from '../types';

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  allow_self_registration: true,
  require_profile_approval: false,
  free_plan_photo_limit: 6,
  pro_plan_photo_limit: 30,
  free_plan_monthly_views: 100, // limite de 100 acessos no plano Free
  pro_plan_monthly_views: 2500, // limite de 2500 acessos no plano PRO
  price_pro_monthly: 29.90,
  price_pro_yearly: 290.00,
  admin_pix_key: 'georgefctec@gmail.com',
  admin_pix_name: 'George - TécnicoLink SaaS',
  admin_whatsapp_billing: '5541999998888',
  enable_access_paywall: true,
  enable_verified_badges: true,
  maintenance_mode: false,
  enable_watermark: true,
};

export const ADMIN_MASTER_PROFILE: Profile = {
  id: 'prof-admin',
  user_id: 'user-admin',
  full_name: 'George Ferreira Costa (Admin Master)',
  username: 'george-admin',
  profession: 'Gestor & Administrador da Plataforma',
  specialties: ['Gestão de Plataforma', 'Moderação', 'Aprovação de Técnicos', 'Configuração Supabase'],
  whatsapp_number: '(41) 99999-8888',
  phone_number: '(41) 99999-8888',
  bio_short: 'Conta de Administrador Master do TécnicoLink. Controle total sobre perfis, limites de planos, moderação de fotos e políticas de segurança.',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  cover_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80',
  city_state: 'Curitiba - PR',
  years_experience: 10,
  accepts_pix: true,
  accepts_cards: true,
  offers_warranty: true,
  rating: 5.0,
  review_count: 99,
  role: 'admin',
  status: 'active',
  plan: 'enterprise',
  is_verified: true,
  max_photos: 100,
  views_count: 1420,
  whatsapp_clicks: 340,
  created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'prof-1',
    user_id: 'user-1',
    full_name: 'Marcos Silva Climatização',
    username: 'marcos-refrigeracao',
    profession: 'Técnico em Refrigeração & Ar-Condicionado',
    specialties: ['Instalação Split Inverter', 'Higienização Química', 'Carga de Gás R410/R32', 'Contratos PMOC'],
    whatsapp_number: '(11) 98455-1234',
    phone_number: '(11) 98455-1234',
    bio_short: 'Especialista em climatização residencial e comercial. Instalações com bomba de vácuo, teste de estanqueidade com nitrogênio e 1 ano de garantia.',
    avatar_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
    city_state: 'São Paulo - SP',
    years_experience: 9,
    accepts_pix: true,
    accepts_cards: true,
    offers_warranty: true,
    rating: 5.0,
    review_count: 54,
    role: 'technician',
    status: 'active',
    plan: 'pro',
    is_verified: true,
    max_photos: 30,
    views_count: 780,
    whatsapp_clicks: 194,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prof-2',
    user_id: 'user-2',
    full_name: 'Felipe Santos Cell',
    username: 'felipe-smartphones',
    profession: 'Manutenção de Celulares & Smartphones',
    specialties: ['Troca de Telas & Baterias', 'Reparo de Placas iPhone/Android', 'Troca de Vidro Apple Watch', 'Desoxidação'],
    whatsapp_number: '(21) 99881-3322',
    phone_number: '(21) 99881-3322',
    bio_short: 'Laboratório técnico com bancada antiestática e microscópio trinocular. Troca de telas na hora com peças originais e garantia expressa.',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80',
    city_state: 'Rio de Janeiro - RJ',
    years_experience: 7,
    accepts_pix: true,
    accepts_cards: true,
    offers_warranty: true,
    rating: 4.9,
    review_count: 68,
    role: 'technician',
    status: 'active',
    plan: 'pro',
    is_verified: true,
    max_photos: 30,
    views_count: 615,
    whatsapp_clicks: 162,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prof-3',
    user_id: 'user-3',
    full_name: 'Eng. Renato Prado Eletrônica',
    username: 'renato-eletronica',
    profession: 'Técnico em Eletrônica & Placas',
    specialties: ['Conserto Smart TVs 4K/OLED', 'Fontes Chaveadas', 'Inversores de Frequência', 'Microsoldagem SMD/BGA'],
    whatsapp_number: '(31) 98712-4400',
    phone_number: '(31) 98712-4400',
    bio_short: 'Diagnóstico preciso em osciloscópio digital e estação de retrabalho BGA. Reparo de módulos industriais, nobreaks de alta potência e placas de TVs modernas.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    city_state: 'Belo Horizonte - MG',
    years_experience: 14,
    accepts_pix: true,
    accepts_cards: true,
    offers_warranty: true,
    rating: 5.0,
    review_count: 42,
    role: 'technician',
    status: 'active',
    plan: 'pro',
    is_verified: true,
    max_photos: 30,
    views_count: 530,
    whatsapp_clicks: 128,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'prof-4',
    user_id: 'user-4',
    full_name: 'Lucas Designer 3D',
    username: 'lucas-modelagem3d',
    profession: 'Modelagem 3D & Prototipagem',
    specialties: ['Impressão 3D Resina e FDM', 'Modelagem Paramétrica CAD', 'Colecionáveis & Miniaturas', 'Peças Sob Medida'],
    whatsapp_number: '(41) 99182-7766',
    phone_number: '(41) 99182-7766',
    bio_short: 'Criação de modelos 3D industriais, moldes e estátuas de alta definição. Impressões em altíssima resolução com pós-processamento profissional e pintura.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1633493763531-155e9754f9d2?auto=format&fit=crop&w=1200&q=80',
    city_state: 'Curitiba - PR',
    years_experience: 6,
    accepts_pix: true,
    accepts_cards: true,
    offers_warranty: true,
    rating: 4.9,
    review_count: 31,
    role: 'technician',
    status: 'active',
    plan: 'pro',
    is_verified: true,
    max_photos: 30,
    views_count: 440,
    whatsapp_clicks: 98,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'prof-5',
    user_id: 'user-5',
    full_name: 'Juliana Bolos & Doces Finos',
    username: 'juliana-confeitaria',
    profession: 'Confeitaria Artística de Festas',
    specialties: ['Bolos Decorados em Chantininho', 'Doces Finos para Casamentos', 'Kit Festa Personalizado', 'Macarons Franceses'],
    whatsapp_number: '(51) 99344-5511',
    phone_number: '(51) 99344-5511',
    bio_short: 'Transformando momentos especiais em sabores inesquecíveis. Bolos artísticos sob encomenda com ingredientes premium, chocolates nobres e finalização impecável.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    cover_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1200&q=80',
    city_state: 'Porto Alegre - RS',
    years_experience: 8,
    accepts_pix: true,
    accepts_cards: true,
    offers_warranty: true,
    rating: 5.0,
    review_count: 89,
    role: 'technician',
    status: 'active',
    plan: 'pro',
    is_verified: true,
    max_photos: 30,
    views_count: 920,
    whatsapp_clicks: 275,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  }
];

export const INITIAL_GALLERY: Record<string, ServicePhoto[]> = {
  'prof-1': [
    {
      id: 'photo-101',
      profile_id: 'prof-1',
      image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
      title: 'Instalação de Ar Split Inverter 18.000 BTUs',
      description: 'Instalação técnica com tubulação 100% cobre flangeada, vácuo de 500 microns e isolamento térmico blindado.',
      tag: 'Instalação',
      created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'photo-102',
      profile_id: 'prof-1',
      image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
      title: 'Higienização Química com Bactericida Certificado',
      description: 'Desmontagem da turbina e serpentina para limpeza profunda, eliminando 99,9% de ácaros, fungos e odores.',
      tag: 'Manutenção',
      created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      id: 'photo-103',
      profile_id: 'prof-1',
      image_url: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?auto=format&fit=crop&w=800&q=80',
      title: 'Manutenção de Condensadora Multi Split',
      description: 'Substituição de capacitor de partida e recarga de fluido refrigerante ecológico R410A balançeada por peso.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    },
    {
      id: 'photo-104',
      profile_id: 'prof-1',
      image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      title: 'Infraestrutura Embutida para Ar-Condicionado',
      description: 'Passagem de dreno em PVC rígido e linha frigorígena embutida em alvenaria antes da pintura.',
      tag: 'Instalação',
      created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    }
  ],
  'prof-2': [
    {
      id: 'photo-201',
      profile_id: 'prof-2',
      image_url: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
      title: 'Troca de Tela OLED iPhone 14 Pro na Hora',
      description: 'Substituição com tela de alta taxa de atualização, mantendo True Tone e vedação contra respingos de água.',
      tag: 'Manutenção',
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'photo-202',
      profile_id: 'prof-2',
      image_url: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
      title: 'Microsoldagem de Conector de Carga Tipo-C',
      description: 'Restauração de trilhas rompidas em placa mãe com máscara UV e solda em pasta de baixa fusão.',
      tag: 'Manutenção',
      created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'photo-203',
      profile_id: 'prof-2',
      image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
      title: 'Troca de Bateria Original com 100% de Saúde',
      description: 'Substituição segura com programação do chip serial para exibição de saúde da bateria sem alertas.',
      tag: 'Instalação',
      created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    }
  ],
  'prof-3': [
    {
      id: 'photo-301',
      profile_id: 'prof-3',
      image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
      title: 'Conserto de Placa Principal Smart TV 4K',
      description: 'Substituição de chipset com estação de retrabalho infravermelho e reprogramação de memória EPROM.',
      tag: 'Manutenção',
      created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'photo-302',
      profile_id: 'prof-3',
      image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      title: 'Reparo de Inversor de Frequência Industrial',
      description: 'Troca do banco de capacitores eletrolíticos e módulos IGBT com teste de carga em bancada.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    }
  ],
  'prof-4': [
    {
      id: 'photo-401',
      profile_id: 'prof-4',
      image_url: 'https://images.unsplash.com/photo-1633493763531-155e9754f9d2?auto=format&fit=crop&w=800&q=80',
      title: 'Impressão 3D em Resina 8K de Alta Definição',
      description: 'Estátua colecionável com detalhes microscópicos, curada em câmara UV e primer para pintura.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    },
    {
      id: 'photo-402',
      profile_id: 'prof-4',
      image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
      title: 'Prototipagem de Peça Mecânica em ABS e Nylon',
      description: 'Engrenagens resistentes e carcaças funcionais para testes de encaixe e validação de engenharia.',
      tag: 'Instalação',
      created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    }
  ],
  'prof-5': [
    {
      id: 'photo-501',
      profile_id: 'prof-5',
      image_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
      title: 'Bolo Floral Artístico de 3 Andares para Casamento',
      description: 'Massa amanteigada de baunilha com recheio de frutas vermelhas e cobertura aveludada em chantininho espatulado.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'photo-502',
      profile_id: 'prof-5',
      image_url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
      title: 'Mesa de Doces Finos & Brigadeiros Gourmet',
      description: 'Brigadeiros belgas com castanha-do-pará, camafeu de nozes e trufas artesanais banhadas em ouro comestível.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
    {
      id: 'photo-503',
      profile_id: 'prof-5',
      image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
      title: 'Bolo Temático Infantil com Escultura em Açúcar',
      description: 'Decoração personalizada com modelagem manual em pasta americana e bolo molhadinho de brigadeiro.',
      tag: 'Acabamento',
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    }
  ]
};

export const INITIAL_TESTIMONIALS: Record<string, Testimonial[]> = {
  'prof-1': [
    {
      id: 'test-1',
      profile_id: 'prof-1',
      client_name: 'Juliana Mendes',
      client_neighborhood: 'Moema, São Paulo',
      comment: 'O Marcos instalou 3 aparelhos de ar split no meu apartamento. Fez todo o teste de vácuo, não deixou nem poeira na parede e o atendimento foi rápido!',
      rating: 5,
      service_type: 'Instalação Split Inverter',
      date: 'Há 1 semana'
    },
    {
      id: 'test-2',
      profile_id: 'prof-1',
      client_name: 'Roberto Alencar',
      client_neighborhood: 'Pinheiros, São Paulo',
      comment: 'Excelente técnico. Higienizou o ar-condicionado do meu escritório e acabou de vez com o cheiro de umidade.',
      rating: 5,
      service_type: 'Higienização Química',
      date: 'Há 3 semanas'
    }
  ],
  'prof-2': [
    {
      id: 'test-201',
      profile_id: 'prof-2',
      client_name: 'Camila Vasconcelos',
      client_neighborhood: 'Barra da Tijuca, RJ',
      comment: 'Trocou a tela do meu iPhone em menos de 40 minutos com peça original. O touch ficou perfeito e ele me deu garantia de 6 meses.',
      rating: 5,
      service_type: 'Troca de Tela iPhone',
      date: 'Há 3 dias'
    }
  ],
  'prof-5': [
    {
      id: 'test-501',
      profile_id: 'prof-5',
      client_name: 'Fernanda Diniz',
      client_neighborhood: 'Moinhos de Vento, Porto Alegre',
      comment: 'O bolo de aniversário da minha filha foi a atração da festa! Além de lindo de tirar o fôlego, o sabor estava divino e super molhadinho.',
      rating: 5,
      service_type: 'Bolo Artístico Infantil',
      date: 'Há 5 dias'
    }
  ]
};
